project:
  type: website
  resources:
   - assets/*

website:
  title: "Radar plot for mcmc output"
  reader-mode: true
  site-url: "https://robertahrens.github.io/radar_plot_mcmc" 
  repo-url: "https://github.com/robertahrens/radar_plot_mcmc"
  repo-actions: [source, issue]
  search: true
  back-to-top-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/robertahrens/radar_plot_mcmc
    contents: 
      - text: "Home"
        file: assets/quarto-doc.qmd
format: 
  html:
    toc: true
    toc-expand: false
    theme:
      - default
